# Generated by Django 3.2.7 on 2021-09-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='img_name',
        ),
    ]
